version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: petland_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=petland
    networks:
      - primeira-network

  petland:
    build:
        context: .
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    networks:
      - primeira-network

networks:
  primeira-network:
    driver: bridge

volumes:
    postgres_data: